### ISSUE TITLE
feat: add plugin for git

### ISSUE THREAD

**Issue by tsirysndr** [tsirysndr/repl#1]
See https://github.com/tsirysndr/repl/blob/main/docker.ts

**Comment by milinddethe15** [comment]
Hi, I want to work on this issue. Assign it to me.

**Comment by tsirysndr** [comment]
Hi @milinddethe15 ,

Thank you for your interest in contributing to our project! I appreciate your willingness to help. To get started, please follow these steps:

1. Fork the repository to your own GitHub account.
2. Clone the forked repository to your local machine.
3. Create a new branch for your work (e.g., `git checkout -b issue-XX` where XX is the issue number).
4. Make your changes and commits.
5. Push your changes to your forked repository.
6. Open a pull request from your forked repository to our main repository's branch related to the issue .

Once you've completed these steps, our team will review your pull request and provide feedback. If everything looks good, we'll merge it into the main codebase.

If you have any questions or need further guidance, feel free to ask. Good luck with your contribution!

Best regards,
Tsiry Sandratraina
