### ISSUE TITLE
feat: add plugin for `deno`

### ISSUE THREAD

**Issue by tsirysndr** [tsirysndr/repl#20]
See:
https://github.com/tsirysndr/repl/blob/main/plugins/docker.ts
https://docs.deno.com/runtime/manual/getting_started/command_line_interface

**Comment by Siddharth9890** [comment]
hey @tsirysndr can i work on this?

**Comment by tsirysndr** [comment]
Hi @Siddharth9890  ,

Thank you for your interest in contributing to our project! I appreciate your willingness to help. To get started, please follow these steps:

Fork the repository to your own GitHub account.
Clone the forked repository to your local machine.
Create a new branch for your work (e.g., git checkout -b issue-XX where XX is the issue number).
Make your changes and commits.
Push your changes to your forked repository.
Open a pull request from your forked repository to our main repository's branch related to the issue .
Once you've completed these steps, our team will review your pull request and provide feedback. If everything looks good, we'll merge it into the main codebase.

If you have any questions or need further guidance, feel free to ask. Good luck with your contribution!

Best regards,
Tsiry Sandratraina
